export default {
  home: require('./home.png'),
  profile: require('../assests/profile.png'),
  donate: require('../assests/donate.png'),
  paneera: require('../assests/paneera.png'),
  history: require('../assests/history.png'),
  subscription: require('../assests/subscription.png'),
  TaxDeduction: require('../assests/TaxDeduction.png'),
  PrivacyPolicy: require('../assests/PrivacyPolicy.png'),
  Logout: require('../assests/Logout.png'),
  addMore: require('../assests/addMore.png'),
  checkBox: require('../assests/checkBox.png'),
  donees1: require('../assests/donees1.png'),
  donees2: require('../assests/donees2.png'),
  profileVector: require('../assests/profileVector.png'),
  backButton: require('../assests/backButton.png'),
  profileimage: require('../assests/profileimage.png'),
  summaryDetailsImg: require('../assests/summaryDetailsImg.png'),
  Close_Icon: require('../assests/Close_Icon.png'),
  Call_Icon: require('../assests/Call_Icon.png'),
  Estimated_Time: require('../assests/Estimated_Time.png'),
  Distance_from: require('../assests/Distance_from.png'),
  Time_distance: require('../assests/Time_distance.png'),
  Tick_Vector: require('../assests/Tick_Vector.png'),
  Details_Icon: require('../assests/Details_Icon.png'),
  minus_Vector: require('../assests/minus_Vector.png'),
  plussVector: require('../assests/plus_Vector.png'),
  onboarding1: require('../assests/onboarding1.png'),
  onboarding2: require('../assests/onboarding2.png'),
  onboarding3: require('../assests/onboarding3.png'),
  Filter: require('../assests/Filter.png'),
  bgModalImage: require('../assests/bgModalImage.png'),
  acceptedLottie: require('../assests/acceptedLottie.json'),
  acceptLottie: require('../assests/accept_Lottie.json'),

  // addMore: require("../assests/addmore"),
};
